import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { useKeenSlider } from 'keen-slider/react'


export default function Home() {
  const [sliderRef, sliderInstanceRef] = useKeenSlider({
    dragSpeed: 0.5,
    initial: 0,
    selector: '.slide'
  });

  const scrollPrev = () => {
    sliderInstanceRef.current?.prev();
  };

  const scrollNext = () => {
    sliderInstanceRef.current?.next();
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.carouselViewport}>
          <ul className={styles.carousel} ref={sliderRef}>
            <li className={`${styles.slide} slide`}>slide 1</li>
            <li className={`${styles.slide} slide`}>slide 2</li>
            <li className={`${styles.slide} slide`}>slide 3</li>
          </ul>
        </div>
        <div className={styles.buttons}>
          <button className={styles.button} onClick={scrollPrev}>prev</button>
          <button className={styles.button} onClick={scrollNext}>next</button>
        </div>
      </main>

      
    </div>
  )
}
